### PR TITLE
Add repository url

### PR DESCRIPTION
**Pull request by kudos**
Save people googling the package name to find the repository.

### CODE REVIEW

**Comment by zeke** [comment]
+1

npm is nagging about it too: `npm WARN package.json redis-url@0.3.1 No repository field.`

**Comment by zeke** [comment]
@ddollar I'd be happy to maintain this if you want to collab me on it.

**Comment by kudos** [comment]
@zeke Thanks for volunteering, man.

**Comment by zeke** [comment]
:+1:

**Pull request merged**
